from .gpt_attention import GPTSelfAttention
from .vit_attention import ViTSelfAttention
from .vit_moe_attention import SelfAttentionForMoe
from .transformer_attention import TransformerSelfAttention, TransformerMultiHeadAttention